services:
  nginx:
    image: nginx:1.17
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8000:80
    depends_on:
      - backend
      - frontend

  frontend:
    build:
      target: dev
    stdin_open: true
    volumes:
      - './frontend:/app:cached'
      - './frontend/node_modules:/app/node_modules:cached'
    environment:
      - NODE_ENV=development

  backend:
    command: python app/main.py
    tty: true
    volumes:
      - ./backend:/app/:cached
      - ./.docker/.ipython:/home/appuser/.ipython:cached

  worker:
    command: celery --app app.tasks worker --loglevel=DEBUG -Q main-queue -c 1
    volumes:
      - ./backend:/app/:cached

  migrate:
    volumes:
      - ./backend:/app/:cached

  postgres:
    ports:
      - '5432:5432'

  redis:
    ports:
      - 6379:6379

  flower:
    image: mher/flower
    command: celery flower --broker=redis://redis:6379/0 --port=5555
    ports:
      - 5555:5555
    depends_on:
      - redis
