#!/bin/bash
# Build the images at the current commit, make them available to the LOCAL
# cluster and `helm upgrade --install` the chart. The one command every drill in
# docs/ARCHITECTURE.md §18 and §21 starts from.
#
#   scripts/k8s/deploy-local.sh                    # build + deploy HEAD, --atomic
#   scripts/k8s/deploy-local.sh --no-atomic        # leave a failed rollout visible
#   scripts/k8s/deploy-local.sh --skip-build       # redeploy the current tag
#   scripts/k8s/deploy-local.sh -- --set secrets.SECRET_KEY=   # extra helm args
#
# Refuses to run unless kubectl points at docker-desktop or kind-*.

set -euo pipefail
# shellcheck source=scripts/k8s/lib.sh
source "$(dirname "$0")/lib.sh"

atomic=(--atomic)
build=true
extra=()
while [ $# -gt 0 ]; do
  case "$1" in
    --no-atomic)  atomic=() ;;
    --skip-build) build=false ;;
    --) shift; extra=("$@"); break ;;
    *) die "unknown option: $1" ;;
  esac
  shift
done

require_local_context
cd "$REPO_ROOT"

# --- tag -------------------------------------------------------------------
# The tag names the exact source that was built (§20). A dirty tree is not the
# commit, so it gets a tag that says so instead of borrowing the commit's name.
TAG="sha-$(git rev-parse HEAD)"
if [ -n "$(git status --porcelain -- backend frontend)" ]; then
  TAG="$TAG-dirty-$(date +%s)"
  echo "! backend/ or frontend/ has uncommitted changes; tagging $TAG"
fi
BACKEND_IMAGE="fastapi-react/backend:$TAG"
FRONTEND_IMAGE="fastapi-react/frontend:$TAG"

# --- build and load ----------------------------------------------------------
if $build; then
  docker build -t "$BACKEND_IMAGE" ./backend
  docker build -t "$FRONTEND_IMAGE" --target production ./frontend
  if [ "$CLUSTER_KIND" = kind ]; then
    kind load docker-image "$BACKEND_IMAGE" "$FRONTEND_IMAGE" --name "$KIND_CLUSTER"
  fi
  # Docker Desktop: scripts/k8s/preflight.sh confirms the nodes already see
  # images from `docker build`.
elif ! docker image inspect "$BACKEND_IMAGE" >/dev/null 2>&1; then
  die "--skip-build, but $BACKEND_IMAGE does not exist"
fi

# --- local secrets -----------------------------------------------------------
# Generated once and reused: SECRET_KEY signs every JWT, and Postgres keeps the
# password it was initialised with on its volume. Gitignored; delete it only
# together with the release and its volume (helm uninstall + kubectl delete pvc).
if [ ! -f "$LOCAL_SECRETS" ]; then
  umask 077
  cat > "$LOCAL_SECRETS" <<EOF
# Generated by scripts/k8s/deploy-local.sh for the local cluster. Gitignored.
secrets:
  SECRET_KEY: "$(openssl rand -hex 32)"
  POSTGRES_PASSWORD: "$(openssl rand -hex 24)"
EOF
  echo "generated $LOCAL_SECRETS"
fi

# --- deploy ------------------------------------------------------------------
helm upgrade --install "$RELEASE" "$CHART" \
  -f "$CHART/values-local.yaml" \
  -f "$LOCAL_SECRETS" \
  --namespace "$NAMESPACE" --create-namespace \
  --set image.tag="$TAG" \
  ${atomic[@]+"${atomic[@]}"} --wait --timeout 5m \
  ${extra[@]+"${extra[@]}"}

kubectl get pods -n "$NAMESPACE" -o wide
cat <<EOF

Deployed $TAG to $CONTEXT.
  curl -s http://localhost/api/v1/health/ready
  helm history $RELEASE -n $NAMESPACE

First install only -- create the admin@test.com superuser:
  kubectl exec -n $NAMESPACE deploy/backend -- python app/initial_data.py
EOF
